### ISSUE TITLE
Soft Assertion Query

### ISSUE THREAD

**Issue by Supriyavineeth** [brillout/libassert#2]
Hi brillout,
We are using Cucumber Framework and test cases have been written in Feature Files.

Basically we want to achieve 3 objectives as below:

1.expected vs actual comparison syntax
2.There are 10 steps(lines)of assertion in the feature file and if 5th line fails, the execution should still continue and execute 6th to 10th steps.
3.In the report the failed step(i.e 5th Step) should be clearly marked as "Failed". Thus we can clearly make out 9 out of 10 steps passed and 1 failed.
Please let me know how can I achieve this?

**Comment by brillout** [comment]
Sounds like `reassert` is not what you are looking for
